// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbhVNHQvlESmALmlyLClfhBagTtc2qtv8',
    appId: '1:382244951871:web:b46ce4e0fec2e83874e58a',
    messagingSenderId: '382244951871',
    projectId: 'dicoding-flutter-expert-9b14d',
    authDomain: 'dicoding-flutter-expert-9b14d.firebaseapp.com',
    storageBucket: 'dicoding-flutter-expert-9b14d.firebasestorage.app',
    measurementId: 'G-93MY7WS1CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcl1Npdvb8k-mKN-q5u5732pD-GBADVwY',
    appId: '1:382244951871:android:4425d10cd16f4d1974e58a',
    messagingSenderId: '382244951871',
    projectId: 'dicoding-flutter-expert-9b14d',
    storageBucket: 'dicoding-flutter-expert-9b14d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXnojpEryweHjl8EA1pKfM2NK2mOLs7kk',
    appId: '1:382244951871:ios:2794a34efc77747f74e58a',
    messagingSenderId: '382244951871',
    projectId: 'dicoding-flutter-expert-9b14d',
    storageBucket: 'dicoding-flutter-expert-9b14d.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
